// Prepares the inputs design-sync's converter can't derive from this repo on its own.
//
// Three jobs:
//   1. Inline public/ image assets as data URIs, so the next/image shim can render
//      the logo marks with no server and no network.
//   2. Compile app/globals.css (which starts with @tailwind directives) into static
//      CSS. Shipping the raw file would send @tailwind directives to a browser,
//      which ignores them -- every utility class in the design system would vanish.
//   3. Self-host Inter / Sora / IBM Plex Mono. next/font/google injects these at
//      runtime via --font-inter, --font-sora and --font-mono. Outside Next those
//      variables are undefined and everything falls back to a system face, which
//      silently changes the look of every design built with this system.
//
// Run from the repo root: node .design-sync/build-ds.mjs

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const DS = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(DS, "..");
const CACHE = join(DS, ".cache");
const FONT_DIR = join(DS, "fonts");

mkdirSync(CACHE, { recursive: true });
mkdirSync(FONT_DIR, { recursive: true });

/* ---------------------------------------------------------------- 1. assets */

const MIME = { ".svg": "image/svg+xml", ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg" };

// Only the marks the synced components actually reference. founder.jpg and the
// blog covers are page content, not design-system parts.
const ASSETS = ["icon-light.svg", "roble-media-lab-icon.svg", "logo-light.svg", "logo-dark.svg", "logo.png"];

const entries = ASSETS.filter((name) => existsSync(join(ROOT, "public", name))).map((name) => {
  const buf = readFileSync(join(ROOT, "public", name));
  const mime = MIME[extname(name)] ?? "application/octet-stream";
  return `  "/${name}": "data:${mime};base64,${buf.toString("base64")}"`;
});

writeFileSync(
  join(DS, "shims", "assets.generated.ts"),
  `// GENERATED by .design-sync/build-ds.mjs -- do not edit.\n` +
    `// public/ assets inlined as data URIs so previews need no server.\n` +
    `export const PUBLIC_ASSETS: Record<string, string> = {\n${entries.join(",\n")}\n};\n`
);
console.log(`[assets] inlined ${entries.length} public asset(s)`);

/* ------------------------------------------------------------------ 2. fonts */

const FAMILIES = [
  { name: "Inter", css: "Inter", weights: [400, 500, 600, 700, 800] },
  { name: "Sora", css: "Sora", weights: [400, 600, 700] },
  { name: "IBM Plex Mono", css: "IBM+Plex+Mono", weights: [400, 500, 600] }
];

const fontsCss = join(FONT_DIR, "fonts.css");

if (!existsSync(fontsCss) || readdirSync(FONT_DIR).filter((f) => f.endsWith(".woff2")).length === 0) {
  const query = FAMILIES.map((f) => `family=${f.css}:wght@${f.weights.join(";")}`).join("&");
  const url = `https://fonts.googleapis.com/css2?${query}&display=swap`;
  // A modern UA is what makes Google serve woff2 rather than legacy formats.
  const UA =
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`[fonts] Google Fonts returned ${res.status}. Fetch manually into .design-sync/fonts/.`);
  let css = await res.text();

  // Keep the latin subsets only. The full response carries cyrillic, greek and
  // vietnamese blocks the site never renders; shipping them triples the payload.
  const blocks = css
    .split("/*")
    .map((b) => "/*" + b)
    .filter((b) => /^\/\*\s*latin(-ext)?\s*\*\//.test(b));

  // Inter and Sora ship as variable fonts, so every weight of a family points at
  // the SAME url. Dedupe by url or we download identical bytes once per weight and
  // emit @font-face rules referencing files that were never written under that name.
  const byUrl = new Map();
  const rewritten = [];

  for (const block of blocks) {
    const m = block.match(/url\((https:[^)]+\.woff2)\)/);
    if (!m) continue;
    const url2 = m[1];

    let file = byUrl.get(url2);
    if (!file) {
      const family = (block.match(/font-family:\s*'([^']+)'/)?.[1] ?? "font").replace(/\s+/g, "");
      const sub = /latin-ext/.test(block) ? "latinext" : "latin";
      // Short hash of the url keeps the name 1:1 with the actual file, so a
      // variable font shared across weights resolves to exactly one download.
      const hash = createHash("sha1").update(url2).digest("hex").slice(0, 8);
      file = `${family}-${sub}-${hash}.woff2`;
      const bin = await fetch(url2, { headers: { "User-Agent": UA } });
      if (!bin.ok) throw new Error(`[fonts] failed to download ${url2}`);
      writeFileSync(join(FONT_DIR, file), Buffer.from(await bin.arrayBuffer()));
      byUrl.set(url2, file);
    }
    rewritten.push(block.replace(url2, `./${file}`));
  }

  writeFileSync(
    fontsCss,
    `/* GENERATED by .design-sync/build-ds.mjs -- self-hosted copies of the faces\n` +
      `   next/font/google injects at runtime in the live app. */\n` +
      rewritten.join("\n") +
      "\n"
  );
  console.log(`[fonts] ${rewritten.length} @font-face rule(s) over ${byUrl.size} unique file(s)`);
} else {
  console.log("[fonts] already present, skipping download");
}

/* ------------------------------------------------------------------- 3. CSS */

const out = join(CACHE, "ds-styles.css");
execFileSync("npx", ["tailwindcss", "-i", "app/globals.css", "-o", out, "--minify"], {
  cwd: ROOT,
  stdio: ["ignore", "inherit", "inherit"]
});

// next/font normally defines these three variables on <html>. globals.css reads
// them everywhere, so without this block the compiled CSS points at nothing.
writeFileSync(
  out,
  readFileSync(out, "utf8") +
    `\n:root{--font-inter:"Inter";--font-sora:"Sora";--font-mono:"IBM Plex Mono";}\n` +
    `body{font-family:var(--font-inter),sans-serif;}\n`
);
console.log(`[css] wrote ${out}`);

/* ------------------------------------------------------------ 4. type decls */

// The converter reads each component's prop contract from a .d.ts tree. A Next
// app ships none, which leaves every component typed `[key: string]: unknown` --
// the design agent would know the components exist but nothing about their APIs.
// tsc emits the real declarations (with JSDoc) for the overridden findTypesRoot
// in .design-sync/overrides/dts.mjs to pick up.
//
// Non-fatal by design: type errors elsewhere in the app must not block a sync,
// and declarations are still emitted alongside them.
try {
  execFileSync("npx", ["tsc", "-p", ".design-sync/tsconfig.dts.json"], {
    cwd: ROOT,
    stdio: ["ignore", "ignore", "ignore"]
  });
} catch {
  // emit proceeds despite diagnostics
}
const declCount = existsSync(join(CACHE, "types"))
  ? readdirSync(join(CACHE, "types", "components")).filter((f) => f.endsWith(".d.ts")).length
  : 0;
if (!declCount) throw new Error("[types] no declarations emitted — component props would ship empty");
console.log(`[types] emitted ${declCount} declaration file(s)`);
