import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { CTA } from "@/components/cta";
import { PageHero } from "@/components/page-hero";
import { articles, site } from "@/content/site";

const bodies: Record<string, React.ReactNode> = {
  "where-to-start-with-ai": <><h2>Begin with friction, not software</h2><p>Ask where your team repeats the same low-judgement task, searches for the same information, or loses time moving work between people. Those patterns are more useful than a list of popular AI products.</p><h2>Choose a narrow first use case</h2><p>A focused workflow is easier to test, safer to change, and clearer to measure. Examples might include turning meeting notes into structured actions or drafting a first response that a person reviews.</p><h2>Keep a person responsible</h2><p>AI output needs ownership. Decide who checks accuracy, handles unusual situations, and can turn the system off. Useful automation supports judgement rather than hiding it.</p><h2>Measure the real change</h2><p>Track time saved, error rates, adoption, and the quality of the handoff—not the novelty of the tool. Expand only when the evidence supports it.</p></>,
  "content-system-not-calendar": <><h2>A calendar only records decisions</h2><p>Consistency comes from knowing who the content is for, which business goals it supports, who owns each step, and how learning returns to the plan. A publishing calendar is helpful, but it cannot make those decisions for you.</p><h2>Build the layers beneath it</h2><p>Define a small set of audience problems and content pillars. Create repeatable formats and clear review rules. Then choose a planning rhythm your team can sustain.</p><h2>Make feedback part of the system</h2><p>A useful content system includes a simple way to review audience response, sales conversations, and team effort. The plan should become better informed over time—not merely fuller.</p></>,
  "automation-before-tools": <><h2>Document reality first</h2><p>Write down what triggers the process, which information is required, who makes decisions, what can go wrong, and what a successful result looks like. The awkward exceptions are often more important than the happy path.</p><h2>Remove before you automate</h2><p>Some steps exist only because an old process required them. Simplify, combine, or remove unnecessary work before introducing automation.</p><h2>Design the handoff</h2><p>Every dependable automation needs clear ownership, useful logging, and a way for a person to intervene. That is what turns a clever demo into an operating system a business can trust.</p></>
};
export function generateStaticParams(){return articles.map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const article=articles.find(a=>a.slug===slug);return article?{title:article.title,description:article.description}:{}}
export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const article=articles.find(a=>a.slug===slug);if(!article)notFound();const schema={"@context":"https://schema.org","@type":"Article",headline:article.title,description:article.description,datePublished:article.date,author:{"@type":"Organization",name:site.name},publisher:{"@type":"Organization",name:site.name}};return <><PageHero eyebrow={`${article.readTime} · ${article.date}`} title={article.title}><p>{article.description}</p></PageHero><article className="content-section"><div className="shell narrow prose">{bodies[slug]}</div></article><CTA/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></>}
